import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/shared/navbar";

const workSans = Work_Sans({
	variable: "--font-work-sans",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Portofolio",
	description: "Generated by create next app",
};

export const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => {
	return (
		<html lang="en" className="dark">
			<body className={`${workSans.className} antialiased`}>
				<Navbar />
				{children}
			</body>
		</html>
	);
};
export default RootLayout;
