import Breadcrumbs from "@/components/shared/dashboard/Breadcrumbs";
import FormPortofolio from "@/components/shared/dashboard/portofolio/form-portofolio";
import SiderbarTriggerMobile from "@/components/shared/dashboard/sidebar/sidebar-trigger-mobile";
import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Portofolio | Alif Firmansyah",
	description: "Generated by create next app",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
	return (
		<div className="px-4" id="dashboard-content">
			<header className="flex items-center">
				<SiderbarTriggerMobile />
				<Breadcrumbs
					list={[
						{ href: "/dashboard", label: "dashboard" },
						{ href: "/dashboard/portofolio", label: "portofolio" },
					]}
				/>
			</header>
			<div className="mt-4 sm:px-2 md:px-0">{children}</div>
			<FormPortofolio />
		</div>
	);
};

export default Layout;
