import Breadcrumbs from "@/components/shared/dashboard/Breadcrumbs";
import FormPortofolio from "@/components/shared/dashboard/portofolio/form-portofolio";
import SiderbarTriggerMobile from "@/components/shared/dashboard/sidebar/sidebar-trigger-mobile";
import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Portofolio | Alif Firmansyah",
	description: "Generated by create next app",
};

const Layout = ({
	children,
	modal,
}: {
	children: React.ReactNode;
	modal: React.ReactNode;
}) => {
	return (
		<div className="px-4" id="dashboard-content">
			{modal}
			{children}
			{/* <FormPortofolio /> */}
		</div>
	);
};

export default Layout;
