import Sidebar from "@/components/shared/dashboard/Sidebar";
import { SidebarProvider } from "@/context/SidebarContext";
import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Dashboard | Alif Firmansyah",
	description: "Generated by create next app",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
	return (
		<div className="min-h-screen min-w-full bg-background flex">
			<SidebarProvider>
				<Sidebar />
				<main className="flex-1 p-2">{children}</main>
			</SidebarProvider>
		</div>
	);
};

export default Layout;
