import OverlaySidebar from "@/components/shared/dashboard/sidebar/overlay-sidebar";
import SidebarDekstop from "@/components/shared/dashboard/sidebar/sidebar-dekstop";
import SidebarMobile from "@/components/shared/dashboard/sidebar/sidebar-mobile";
import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Dashboard | Alif Firmansyah",
	description: "Generated by create next app",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
	return (
		<>
			<div className="min-h-[100dvh] bg-background grid grid-cols-1 md:grid-cols-[var(--sidebar-width-md)_minmax(0,1fr)] lg:grid-cols-[var(--sidebar-width_minmax(0,1fr)]">
				{/* <SidebarProvider> */}
				<SidebarDekstop />
				<SidebarMobile />
				<main className="py-4">{children}</main>
				{/* </SidebarProvider> */}
			</div>
			<OverlaySidebar />
		</>
	);
};

export default Layout;
