import { OverlaySidebar } from "@/components/shared/dashboard/Sidebar";
import SidebarDekstop from "@/components/shared/dashboard/sidebar-dekstop";
import SidebarMobile from "@/components/shared/dashboard/sidebar-mobile";
import { SidebarProvider } from "@/context/SidebarContext";
import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Dashboard | Alif Firmansyah",
	description: "Generated by create next app",
};

const Layout = ({ children }: { children: React.ReactNode }) => {
	return (
		<div className="min-h-screen min-w-full bg-background relative">
			<SidebarProvider>
				<SidebarDekstop />
				<OverlaySidebar />
				<main className="relative min-h-screen">{children}</main>
				<SidebarMobile />
			</SidebarProvider>
		</div>
	);
};

export default Layout;
